# Generated by Django 6.0.5 on 2026-05-12 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
        ('sucursales', '0002_sucursales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursales'),
        ),
    ]
