# Generated by Django 6.0.5 on 2026-05-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_sucursal'),
        ('productos', '0003_alter_inventariosucursal_sucursal'),
        ('sucursales', '0002_sucursales'),
        ('usuarios', '0002_alter_usuario_sucursal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sucursal',
        ),
    ]
