# Generated by Django 5.0.6 on 2026-05-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0003_delete_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursales',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
