# Generated by Django 6.0.5 on 2026-05-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_sku',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
    ]
